[package]
name = "husk-dts-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TypeScript declaration file (.d.ts) parser for Husk"

[dependencies]

[dev-dependencies]
