[package]
name = "husk-lexer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Lexer for the Husk programming language"

[dependencies]
