[package]
name = "husk-ast"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Abstract syntax tree definitions for the Husk programming language"

[dependencies]
