[package]
name = "husk-semantic"
version = "0.1.0"
edition = "2024"

[dependencies]
husk-ast = { path = "../husk-ast" }
husk-types = { path = "../husk-types" }
husk-parser = { path = "../husk-parser" }
