[package]
name = "husk-runtime-js"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "JavaScript runtime support for the Husk programming language"

[dependencies]
