[package]
name = "husk-fmt"
version = "0.1.0"
edition = "2024"

[dependencies]
husk-ast = { path = "../husk-ast" }
husk-lexer = { path = "../husk-lexer" }
husk-parser = { path = "../husk-parser" }
thiserror = "1.0"
