[package]
name = "husk-codegen-js"
version = "0.1.0"
edition = "2024"

[dependencies]
husk-ast = { path = "../husk-ast" }
husk-runtime-js = { path = "../husk-runtime-js" }
husk-semantic = { path = "../husk-semantic" }
husk-types = { path = "../husk-types" }
sourcemap = "9"
